# Generated by Django 5.1.3 on 2024-11-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.TextField()),
                ('dis', models.TextField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='NavigationLink',
        ),
    ]
