# Generated by Django 5.1.3 on 2024-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_contact_name_remove_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.TextField(default='dfgh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(default='jiklk'),
            preserve_default=False,
        ),
    ]
